### ISSUE TITLE
Add a licence? 

### ISSUE THREAD

**Issue by yochannah** [tzok/eltetrado#1]
👋  Hi! I came across this package in your paper in BMC Bioinformatics and was wondering - would you consider adding a licence file to allow others to potentially re-use the code? 

More info: 
- why no licence means code can't be reused: https://choosealicense.com/no-permission/
- choosing an appropriate licence: https://choosealicense.com

**Comment by tzok** [comment]
Hi @yochannah. In our article, the license has been stated already to be MIT. You are correct of course that this information should be disclosed publicly also in the GitHub repository. This has just been done with the recent commit https://github.com/tzok/eltetrado/commit/199a8085af9508254a69704190358c2ea3eae5f5
Thanks!
